wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.16.4
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1712730185.0
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      2:
      - 1
      - 4
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      3:
      - 15
      - 23
      4: 3.9.17
      5: 0.16.4
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
Learner:
  desc: null
  value:
    loss_func: MSELoss()
    opt_func: fastai.optimizer.Adam
    lr: 0.001
    splitter: fastai.torch_core.trainable_params
    metrics: null
    path: .
    model_dir: models
    wd: null
    wd_bn_bias: false
    train_bn: true
    moms:
    - 0.95
    - 0.85
    - 0.95
    default_cbs: true
    _name: <fastai.learner.Learner object at 0x7f1ed246b490>
TrainEvalCallback:
  desc: null
  value: true
Recorder:
  desc: null
  value:
    add_time: true
    train_metrics: false
    valid_metrics: true
CastToTensor:
  desc: null
  value: true
ProgressCallback:
  desc: null
  value: true
ConditionalDDPMCallback:
  desc: null
  value:
    n_steps: 1000
    beta_min: 0.0001
    beta_max: 0.02
    cfg_scale: 3
EMA:
  desc: null
  value:
    beta: 0.995
    pct_start: 0.3
ParamScheduler:
  desc: null
  value: true
SaveModelCallback:
  desc: null
  value:
    fname: params
    every_epoch: false
    at_end: false
    with_opt: false
WandbCallback:
  desc: null
  value:
    log: null
    log_preds: false
    log_preds_every_epoch: false
    log_model: true
    model_name: null
    log_dataset: false
    dataset_name: null
    valid_dl: null
    n_preds: 36
    seed: 12345
    reorder: true
n_inp:
  desc: null
  value: 1
input 1 dim 1:
  desc: null
  value: 512
input 1 dim 2:
  desc: null
  value: 1
input 1 dim 3:
  desc: null
  value: 1
input 1 dim 4:
  desc: null
  value: 1280
batch size:
  desc: null
  value: 512
batch per epoch:
  desc: null
  value: 8
model parameters:
  desc: null
  value: 698945
device:
  desc: null
  value: cuda
frozen:
  desc: null
  value: false
frozen idx:
  desc: null
  value: 0
dataset.tfms:
  desc: null
  value: '[Pipeline: load_param, Pipeline: get_label -> Categorize -- {''vocab'':
    None, ''sort'': True, ''add_na'': False}]'
dls.after_item:
  desc: null
  value: 'Pipeline: ToTensor'
dls.before_batch:
  desc: null
  value: 'Pipeline: '
dls.after_batch:
  desc: null
  value: 'Pipeline: '
