wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.16.4
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1712727308.0
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      2:
      - 1
      - 4
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      3:
      - 15
      - 23
      4: 3.9.17
      5: 0.16.4
      8:
      - 2
      - 5
      13: linux-x86_64
